version: 2.1

jobs:
  run_checkstyle:
    working_directory: /tmp/repos/cmo-metadb
    machine:
	image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Pull cmo metadb common code
          command: |
              export METADB_COMMON_VERSION=$(grep 'cmo_metadb_common\.version' pom.xml | head -1 | sed 's/<cmo_metadb_common\.version>//g' | sed 's|</cmo_metadb_common\.version>||' | tr -d '[:blank:]' | cut -f1) && \
              export METADB_COMMON_ORG=$(grep 'cmo_metadb_common\.group' pom.xml | head -1 | sed 's/<cmo_metadb_common\.group>//g' | sed 's|</cmo_metadb_common\.group>||' | tr -d '[:blank:]' | cut -d. -f3) && \
              cd .. && \
              git clone https://github.com/$METADB_COMMON_ORG/cmo-metadb-common.git && \
              cd cmo-metadb-common && \
              git fetch --tags && \
              git checkout ${METADB_COMMON_VERSION}
      - run:
          name: "Build project and run checkstyle plugin..."
          command: mvn clean install
      - run:
          name: "Running checkstyle plugin..."
          command: mvn checkstyle:checkstyle
      - run:
          name: "Validating checkstyle plugin report..."
          command: bash /tmp/repos/cmo-metadb-common/test/scripts/generate_checkstyle_report.sh /tmp/repos/cmo-metadb
      - store_artifacts:
          path: /tmp/repos/cmo-metadb/checkstyle_report_compiled.txt
          destination: /checkstyle_report.txt

workflows:
  run_mvn_checkstyle:
    jobs:
      - run_checkstyle
