version: 2.1

jobs:
  run_checkstyle:
    working_directory: /tmp/repos/smile-server
    machine:
      image: ubuntu-2004:2024.05.1
    steps:
      - checkout
      - run:
          name: "Build project and run checkstyle plugin..."
          command: mvn clean install
      - run:
          name: "Running checkstyle plugin..."
          command: mvn checkstyle:checkstyle
      - run:
          name: "Validating checkstyle plugin report..."
          command: bash test/scripts/generate_checkstyle_report.sh /tmp/repos/smile-server
      - store_artifacts:
          path: /tmp/repos/smile-server/checkstyle_report_compiled.txt
          destination: /checkstyle_report.txt

workflows:
  run_mvn_checkstyle:
    jobs:
      - run_checkstyle
